blueprint:
  name: Định vị ô tô thông minh
  description: Tự động phát hiện ô tô về nhà và mở cửa. Module định vị ô tô là module định vị ô tô đã mua từ JAVIS
  domain: automation
  input:
    sensor_entity1:
      name: sensor ảo
      selector:
        entity:
          domain: sensor
    switch_entity2:
      name: module định vị ô tô
      selector:
        entity:
          domain: switch
variables:
  sensor_entity1: !input sensor_entity1
  switch_entity2: !input switch_entity2
condition: []
trigger:
  - platform: time_pattern
    id: check_on
    seconds: /3
  - platform: time_pattern
    id: check_off
    seconds: /20
action:
  - choose:
    - conditions: 
        - condition: trigger
          id: check_on
        - condition: state
          entity_id: !input sensor_entity1
          state: 'on'
      sequence:
      - service: mqtt.publish
        data:
          topic_template: "zigbee2mqtt/{{ switch_entity2.split('.')[1] }}/get"
          payload: '{"state": ""}'
  - choose:
    - conditions: 
        - condition: trigger
          id: check_off
        - condition: state
          entity_id: !input sensor_entity1
          state: 'off'
      sequence:
      - service: mqtt.publish
        data:
          topic_template: "zigbee2mqtt/{{ switch_entity2.split('.')[1] }}/get"
          payload: '{"state": ""}'
    default:
      - choose: []
        default: []
mode: single 
max_exceeded: silent
