blueprint:
  name: Tự động nhà vệ sinh
  description: Tự động bật tắt đèn vệ sinh dựa trên 1 cảm biến cửa và 1 cảm biến chuyển
    động
  domain: automation
  input:
    target_switch_1:
      name: Đèn, công tắc, quạt vệ sinh
      description: Chọn đèn, công tắc hoặc quạt thông gió trong phòng vệ sinh
      selector:
        entity:
          domain:
           - switch
           - light
           - fan
          multiple: true
    trigger_motion_sensor:
      name: Cảm biến chuyển động 
      description: Chọn 1 cảm biến chuyển động trong phòng vệ sinh
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
          multiple: false
    trigger_door_sensor:
      name: Cảm biến cửa
      description: Chọn 1 cảm biến cửa trong phòng vệ sinh
      selector:
        entity:
          domain: binary_sensor
          device_class: door
          multiple: false
    door_open_wait:
      name: Thời gian chờ khi mở cửa rồi mới tắt đèn
      description: Thời gian chờ khi mở cửa rồi mới tắt đèn
      default: 2
      selector:
        number:
          min: 0.0
          max: 120.0
          unit_of_measurement: seconds
          step: 1.0
          mode: slider
    no_motion_wait:
      name: Thời gian tắt đèn khi cửa mở mà không có chuyển động
      description: Thời gian tắt đèn khi cửa mở mà không có chuyển động
      default: 120
      selector:
        number:
          min: 0.0
          max: 300.0
          unit_of_measurement: seconds
          step: 1.0
          mode: slider
    no_motion_door_close_wait:
      name: Thời gian chờ tắt đèn khi cửa đóng mà không có chuyển động
      description: Khi cửa đang đóng và không có chuyển động thì sẽ tắt sau 1 khoảng thời gian
      default: 600
      selector:
        number:
          min: 1.0
          max: 1800
          unit_of_measurement: seconds
          step: 1.0
          mode: slider
    from_time:
      name: Thời gian bắt đầu hiệu lực
      description: Bắt đầu khoảng thời gian có hiệu lực
      default: "00:00:00"
      selector:
        time:
    to_time:
      name: Thời gian kết thúc hiệu lực
      description: Bắt đầu khoảng thời gian có hiệu lực
      default: "23:59:59"
      selector:
        time:
  source_url: https://raw.githubusercontent.com/javishome/blueprint/main/blueprint_bathroom_auto.yaml
variables:
  trigger_motion_sensor: !input trigger_motion_sensor
  trigger_door_sensor: !input trigger_door_sensor
  door_open_wait: !input door_open_wait
  target_switch_1: !input target_switch_1
  no_motion_door_close_wait: !input no_motion_door_close_wait
  no_motion_wait: !input no_motion_wait
  from_time: !input from_time
  to_time: !input to_time
  
trigger:
- platform: state
  entity_id: !input trigger_motion_sensor
  from: 'off'
  to: 'on'
  id: motion_on
- platform: state
  entity_id: !input trigger_motion_sensor
  from: 'on'
  to: 'off'
  id: motion_off
- platform: state
  entity_id: !input trigger_motion_sensor
  from: 'on'
  to: 'off'
  for: !input no_motion_wait
  id: no_motion_wait
- platform: state
  entity_id: !input trigger_door_sensor
  from: 'off'
  to: 'on'
  id: door_on
- platform: state
  entity_id: !input trigger_door_sensor
  from: 'on'
  to: 'off'
  id: door_off
- platform: state
  entity_id: !input trigger_door_sensor
  from: 'on'
  to: 'off'
  for: !input no_motion_door_close_wait
  id: door_close_wait
action:
- choose:
  - conditions:
    - condition: trigger
      id: motion_on
    - condition: time
      before: !input to_time
      after: !input from_time
    sequence:
    - service: homeassistant.turn_on
      target:
        entity_id: !input target_switch_1
- choose:
  - conditions:
    - condition: trigger
      id: no_motion_wait
    - condition: time
      before: !input to_time
      after: !input from_time
    sequence:
    - service: homeassistant.turn_off
      target:
        entity_id: !input target_switch_1
- choose:
  - conditions:
    - "{{ expand(target_switch_1) | selectattr('state', '==', 'on') | list | count > 0 }}"
    - condition: trigger
      id: door_close_wait
    - condition: time
      before: !input to_time
      after: !input from_time
    - condition: state
      entity_id: !input trigger_motion_sensor
      state: 'off'
    sequence:
    - service: homeassistant.turn_off
      target:
        entity_id: !input target_switch_1
- choose: 
  - conditions:
    - "{{ expand(target_switch_1) | selectattr('state', '==', 'on') | list | count == 0 }}"
    - condition: trigger
      id: door_on
    - condition: time
      before: !input to_time
      after: !input from_time
    sequence:
      - service: homeassistant.turn_on
        target:
          entity_id: !input target_switch_1
- choose: 
  - conditions:
    - "{{ expand(target_switch_1) | selectattr('state', '==', 'on') | list | count > 0 }}"
    - condition: trigger
      id: door_on
    - condition: time
      before: !input to_time
      after: !input from_time
    sequence:
      - delay: 
          seconds: '{{ door_open_wait | int(0) }}'
      - service: homeassistant.turn_off
        target:
          entity_id: !input target_switch_1