blueprint:
  name: Tắt thiết bị nếu sensor thời gian vượt ngưỡng
  description: Tự động tắt thiết bị nếu sensor thời gian vượt quá giới hạn định sẵn.
  domain: automation
  input:
    time_sensor:
      name: Cảm biến thời gian sử dụng
      selector:
        entity:
          domain: sensor

    max_time:
      name: Giới hạn thời gian (phút)
      default: 60
      selector:
        number:
          min: 1
          max: 10000
          unit_of_measurement: phút
          mode: box

    target_device:
      name: Thiết bị cần tắt
      selector:
        entity:
          domain:
            - switch
            - media_player
            - light
          multiple: true

    extra_actions:
      name: Hành động bổ sung (tùy chọn)
      default: []
      selector:
        action: {}

trigger:
  - platform: state
    entity_id: !input time_sensor

variables:
  sensor_value: "{{ states(!input time_sensor) | float(0) }}"
  max_hours: "{{ (float(!input max_time)) / 60 }}"
  last_triggered: "{{ state_attr(this.entity_id, 'last_triggered') }}"

condition:
  - condition: template
    value_template: >-
      {{ sensor_value > max_hours and (last_triggered is none or now().date() != last_triggered.date()) }}

action:
  - service: homeassistant.turn_off
    target:
      entity_id: !input target_device
  - choose: []
    default: !input extra_actions

mode: single
