blueprint:
  name: Đồng bộ 2 chiều công tắc
  description: Đồng bộ trạng thái giữa 2 công tắc
  domain: automation
  input:
    switch_1:
      name: Switch 1
      selector:
        entity:
          domain:
            - light
            - switch
          multiple: false
    switch_2:
      name: Switch 2
      selector:
        entity:
          domain:
            - light
            - switch
          multiple: false
  source_url: https://raw.githubusercontent.com/javishome/blueprint/main/sync_switch_2way.yaml 
variables:
  switch_1: !input switch_1
  switch_2: !input switch_2
trigger:
  - platform: state
    entity_id:
      - !input switch_1
    from: "on"
    to: "off"
    id: check_off_1
  - platform: state
    entity_id:
      - !input switch_2
    from: "on"
    to: "off"
    id: check_off_2
  - platform: state
    entity_id:
      - !input switch_1
    from: "off"
    to: "on"
    id: check_on_1
  - platform: state
    entity_id:
      - !input switch_2
    from: "off"
    to: "on"
    id: check_on_2
action:
  - choose:
      - conditions:
          - condition: trigger
            id: check_on_1
          - condition: state
            entity_id: !input switch_2
            state: "off"
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: !input switch_2
  - choose:
      - conditions:
          - condition: trigger
            id: check_on_2
          - condition: state
            entity_id: !input switch_1
            state: "off"
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: !input switch_1
  - choose:
      - conditions:
          - condition: trigger
            id: check_off_1
          - condition: state
            entity_id: !input switch_2
            state: "on"
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: !input switch_2
  - choose:
      - conditions:
          - condition: trigger
            id: check_off_2
          - condition: state
            entity_id: !input switch_1
            state: "on"
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: !input switch_1
    default:
      - choose: []
        default: []
mode: single
max_exceeded: silent
